name: StupidCheck
version: '1.0.0'
main: io.Sriptirc_wp_1242.stupidcheck.Stupidcheck
api-version: '1.16'
authors: ['wp:1242']
description: '玩家必须在限定时间内发送特定消息，否则会被杀死'
commands:
    stupidcheck:
        description: '查看插件状态和帮助'
        aliases: ['sc']
permissions:
    stupidcheck.bypass:
        description: '豁免检查权限'
        default: false
    stupidcheck.reload:
        description: '重载插件配置权限'
        default: false
    stupidcheck.admin:
        description: '管理员权限'
        default: false
